version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  api:
    build: .
    container_name: api-nodejs
    environment:
      MONGO_URI: mongodb://host.docker.internal:27017/SoldOut
      REDIS_URL: redis://redis:6379
      PORT: 8085
    ports:
      - "8085:8085"
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
    command: npm start

volumes:
  mongo-data:
